[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mess = "3o3K93TeUMRxrcsWf2Eu6E7oX41Ffx9AWcxEZqC6KEqg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "mess-wallet.json"

[scripts]
test = "bunx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
