[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mess = "MESSnvM44121e2dm4u6HDaTqdn4qGrLjBKqd2uhfEPk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "mess-wallet.json"

[scripts]
test = "bun test --timeout 1000000"
